name: pokedex
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  badges: ^3.0.2
  bloc: ^8.1.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  flutter_shake_animated: ^0.0.5
  get_it: ^7.2.0
  google_fonts: ^4.0.1
  infinite_scroll_pagination: ^3.2.0
  skeletons: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true